language: python

python:
  - 2.7
  - 3.3

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH

install:
  - conda update conda --yes
  - conda create --name testenv --yes python=$TRAVIS_PYTHON_VERSION matplotlib pandas pip six nose openpyxl
  - source activate testenv
  - pip install coveralls
  - pip install .
  - cp test/matplotlibrc .

script:
  - nosetests --verbose --with-id --with-coverage --cover-package=metar

after_success:
  - coveralls
